use_frameworks!

target 'MyCustomStringConvertible_Example' do
  pod 'MyCustomStringConvertible', :path => '../'

  target 'MyCustomStringConvertible_Tests' do
    inherit! :search_paths

    
  end
end
